image: node:10.14.1

clone:
    depth: full

pipelines:
    branches:
        develop:
            - step:
                caches:
                    - node
                script:
                    - npm install --unsafe-perm
                    - unset CI
                    - npm run build
                    - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING.git develop:master
        master:
            - step:
                caches:
                    - node
                script:
                    - npm install --unsafe-perm
                    - unset CI
                    - npm run build
                    - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION.git master:master